spring:
  application:
    name: app-shell
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        healthCheckPath: /health-check
        healthCheckInterval: 20s
        instanceId: ${spring.application.name}:${random.value}
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 80
  error:
    whitelabel:
      enabled: true

logging:
  level:
    org.springframework.web: INFO
    org.springframework.cloud.netflix: DEBUG
    com.mf.appshell: TRACE
    org.springframework.data.elasticsearch: DEBUG

zuul:
  ignoredServices: "*"
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  #  sensitiveHeaders: Cookie,Set-Cookie
  debug:
    request: true
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  ribbon:
    eager-load:
      enabled: false
  routes:
    auth-service:
      path: /auth/**
      serviceId: auth-service
      sensitiveHeaders: Cookie,Set-Cookie
    history-service:
      path: /history/**
      serviceId: history-service-ui
      stripPrefix: true
    stocks-service-ui:
      path: /stocks/**
      serviceId: stocks-service-ui
      stripPrefix: true
    user-account-service-ui:
      path: /user-account/**
      serviceId: user-account-service-ui
      stripPrefix: true

#auth-service:
#  ribbon:
#    listOfServers: http://localhost:9091/api
#    ReadTimeout: 60000
#    ConnectTimeout: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  ServerListRefreshInterval: 1000
  eureka:
    enabled: false

# Secret to generate tokens, used in both auth service and in gateway
auth-service:
  jwtSecret: a3ZzApRSDQF5E9cH3JFV1LNBzOtQEiv6OumGJudd3Ao=

management:
  endpoints:
    web:
      exposure:
        include: 'routes'
