spring:
  application:
    name: app-shell
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8080
  error:
    whitelabel:
      enabled: true

logging:
  level:
    org.springframework.web: INFO
    org.springframework.cloud.netflix: DEBUG
    com.poc.data: TRACE
    org.springframework.data.elasticsearch: DEBUG
