version: '3.5'

networks:
  lan:

services:
  consul:
    image: consul:latest
    container_name: consul
    networks:
      - lan
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
      - "8300:8300"
      - "8301:8301"
  app-shell:
    build: ./app-shell
    container_name: app-shell
    links:
      - "consul:app-shell"
    depends_on:
      - consul
    networks:
      - lan
    ports:
      - 8088:8088
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    links:
      - "consul:gateway-service"
    depends_on:
      - consul
    networks:
      - lan
    ports:
      - 8765:8765
  auth-service:
    build: ./auth-service
    container_name: auth-service
    links:
      - "consul:auth-service"
    depends_on:
      - consul
    networks:
      - lan
    ports:
      - 9091:9091